site_name: practice_django

# docs_dir: '/d/Dev/practice_django/wiki/docs'

site_dir: 'wiki/build'


# site_url: https://example.com/
nav:

    - index: index.md
    - pip install: pip.md
    - Dev: dev.md
    - settings: settings.md
    - Blog: blog/models.md
    - dev blog: wiki\docs\blog\dev_blog.md





# there: readthedocs
theme:
  name: material


dev_addr:
  127.0.0.1:8200



# markdown_extensions:
    # - toc:
         # permalink: True



markdown_extensions:

  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: True


# сворачивание страниц
collapse_single_pages: True

plugins:
    - search
    - awesome-pages

site_author:
    Androgen

# pip
# pip install mkdocs-awesome-pages-plugin