# Generated by Django 4.2.2 on 2023-06-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_likes_post_reply_alter_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reply',
        ),
    ]
